services:
  mariadb:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: kotlin-spring
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
      - ./config/docker.cnf:/etc/mysql/conf.d/docker.cnf

volumes:
  mariadb-data: